* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
  (setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
  (add-to-list 'org-latex-classes
               '("altacv" "\\documentclass[10pt,letter,ragged2e,withhyper]{altacv}
  
  % Change the page layout if you need to
  \\geometry{left=1.25cm,right=1.0cm,top=1.5cm,bottom=1.5cm}
  
  % Use roboto and lato for fonts
  \\renewcommand{\\familydefault}{\\sfdefault}
  
  % Change the colours if you want to
  \\definecolor{SlateGrey}{HTML}{2E2E2E}
  \\definecolor{LightGrey}{HTML}{666666}
  \\definecolor{DarkPastelRed}{HTML}{450808}
  \\definecolor{PastelRed}{HTML}{8F0D0D}
  \\definecolor{GoldenEarth}{HTML}{E7D192}
  \\colorlet{name}{black}
  \\colorlet{tagline}{PastelRed}
  \\colorlet{heading}{DarkPastelRed}
  \\colorlet{headingrule}{GoldenEarth}
  \\colorlet{subheading}{PastelRed}
  \\colorlet{accent}{PastelRed}
  \\colorlet{emphasis}{SlateGrey}
  \\colorlet{body}{LightGrey}
  
  % Change some fonts, if necessary
  \\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
  \\renewcommand{\\personalinfofont}{\\footnotesize}
  \\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
  \\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}
  
  % Change the bullets for itemize and rating marker
  % for \cvskill if you want to
  \\renewcommand{\\itemmarker}{{\\small\\textbullet}}
  \\renewcommand{\\ratingmarker}{\\faCircle}
  "
  
                 ("\\cvsection{%s}" . "\\cvsection*{%s}")
                 ("\\cvevent{%s}" . "\\cvevent*{%s}")))
  (setq org-latex-packages-alist 'nil)
  (setq org-latex-default-packages-alist
        '(("rm" "roboto"  t)
          ("defaultsans" "lato" t)
          ("" "paracol" t)
          ))
#+END_SRC
#+LATEX_CLASS: altacv
#+BEGIN_COMMENT
#+LATEX_HEADER: \columnratio{1.075} % Set the left/right column width ratio to 6:4.
#+END_COMMENT
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
# #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
#+LATEX_HEADER: \addbibresource{aidan.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
#+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings
#+AUTHOR: Gaurav Sood
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Gaurav Sood}
\photoR{2.8cm}{gaurav.jpeg}
\tagline{Sr. Data Scientist}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  \email{gsood.gaurav@gmail.com}
  \phone{+91 9632714987}
  \location{Bangalore, India}
  \github{github.com/gsood-gaurav}
  \linkedin{linkedin.com/in/gsood-gaurav/}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{1}
#+end_export
** Personal Statement Secondmind :ignore:noexport:
#+begin_export latex
 \begin{quote}
 ``I am an aspiring researcher with interests at the intersection of probabilistic machine learning and control theory. I am particularly interested in uncertainty quantification and as a result, a great deal of my work focuses on Bayesian non-parametric methods, specifically Gaussian processes and variational inference.''
 \end{quote}
#+end_export
** Personal Statement Amazon :ignore:
#+begin_export latex
 \begin{quote}
"Senior Data Scientist with total 14 years of experience, and 7 years of experience in Machine Learning, developing open source software in Python, C++, contributing as both individual contributor and team leader, working on Machine Learning, conceptualizing, designing and implementing end to end solutions. Currently working on  Natural Language Processing and Reinforcement Learning. Have used both traditional machine learning methods like Bayesian Networks, Conditional Random Fields and modern deep learning methods LSTMs, Transformer based models like BERT and GPT"
 \end{quote}
#+end_export
** Skills
{{{cvtag(Python)}}}
{{{cvtag(PyTorch)}}}
{{{cvtag(TensorFlow)}}}
{{{cvtag(JAX)}}}
{{{cvtag(Julia)}}}
{{{cvtag(Flux)}}}
{{{cvtag(NumPy)}}}
{{{cvtag(SciPy)}}}
{{{cvtag(Matplotlib)}}}


{{{divider}}}

{{{cvtag(Large Language Models)}}}
{{{cvtag(Generative AI)}}}
{{{cvtag(Probabilistic Modelling)}}}
{{{cvtag(Reinforcement Learning)}}}
{{{cvtag(Open Source Software)}}}
{{{divider}}}

{{{cvtag(Communication)}}}
{{{cvtag(Leadership Skills)}}}

** Experience
*** Sr Data Scientist                                                :ignore:
{{{cvevent(Sr. Data Scientist, HP Inc. June 2021 -- Ongoing, Bangalore\, India)}}}

- Designed and Developed Large Language Models Based application for web content
  filtering acheiving a recall of 0.94
- Implemented evaluation scripts to benchmark LLM application's performance on
  accuracy, cost(token usage) and inference time comparing GPT4/GPT3.5/GPT-4o-mini/GPT-4o
- Mentored three data science interns on Hardware logs analysis using Graph
  Neural Networks and Large Language Models(GPT-2) achieving precision/recall of 0.85/0.73.
- Fine Tuned 4-bit quantized Small language Chat model on custom data set using QLORA
  acheiving an accuracy of 0.96
- Developed Telemetery data analysis pipline using Large Language Model
  embeddings, sentence transformers, UMAP, Variational AutoEncoder and HDBScan
  
{{{cvtag(Prompt Engineering)}}}
{{{cvtag(GPT2)}}}
{{{cvtag(FineTuning)}}}
{{{cvtag(Probabilistic Modelling)}}}
{{{cvtag(Leadership Skills)}}}
{{{cvtag(Graph Nerual Networks)}}}
{{{cvtag(Embedding Models)}}}
*** Software Engineer Machine Learning                               :ignore:
{{{par-div}}}
{{{cvevent(Software Engineer Machine Learning, HP Inc. June 2017 -- 2021, Bangalore\, India)}}}

- Analyzed Sales Time Series Data (Short term/Long term forecasting) using
  Prophet, ARIMA, Gradient Boosting models, studying the effects of Consumer
  Price Index, WholeSale Price Index, Industrial Production Growth and
  employment, hyperparamter tuning using Optuna, producing a MAPE score of 6-8%.
- Worked on HP Personal Systems User Behavior Modelling using Tree Based Models,
  SHAP, UMAP, HDBScan for targeted market campaigning.
- Developed simulator environment for online Reinforcement Learning for
  automated hardware diagnostics.
- Developed Sequence Tagging Model using LSTMs for discovering insights in
  call center records acheiving a precision and recall score of 0.91/0.85
- Mentored 4 interns on sequence tagging using Conditional Random Fields to
  extract insights from call center records.
- Presented and communicated ideas about Probabilistic Modelling and
  Reinforecement Learning to senior leadership
- Analyzed Call center record using Bayesian Networks for predictive diagnostics
  as an aid to call center executives.

{{{cvtag(Time Series Analysis)}}}
{{{cvtag(CART)}}}
{{{cvtag(Reinforcement Learning)}}}
{{{cvtag(Probabilistic Graphical Models)}}}
{{{cvtag(Data Annotation)}}}

{{{new-page}}}

*** Senior Software Engineer :ignore:
{{{par-div}}}
{{{cvevent(Senior Software Engineer, HP Inc. June 2015 -- 2017, Bangalore\, India)}}}
- Designed and Developed a parser for PostScript Language to extract images and
  meta data which was impacting 50000 hp customers and saving 5 million dollars.
- Designed and developed Telemetery module in python.
- Led team of 7 software developers designing and implementing open source
  software used by over 1 million customers.
- Worked on understanding PDF specification, design and implemented PDF document
  processing using PDF libraries like iText and PDFium
- Lead a team of six people which delived Imaging Processing Solutions using
  Python Imaging Library, TessaractOCT to over 10 PSU banks in india
 
{{{cvtag(Algorithms)}}}
{{{cvtag(OpenSource Sofware)}}}
{{{cvtag(Image Processing)}}}
{{{cvtag(Leadership Skills)}}}

*** Software Engineer :ignore:
{{{par-div}}}
{{{cvevent(Software Engineer, HP Inc. June 2010 -- 2015, Bangalore\, India)}}}
- Designed and Implemented Telemetry module in python using asyncio.
- Led team of 7 software developers designing and implementing open source
  software used by over 1 million customers.
- Collaborated with customers and stakeholders, gathering requirements and
  communicating constraints.
- Developed UI, backend, modules in Python for the hp's open source imaging
  solution (https://developers.hp.com/hp-linux-imaging-and-printing)

{{{cvtag(Python)}}}
{{{cvtag(Open Source Software)}}}
{{{cvtag(Asynchronous Programming)}}}

** Certifications
   {{{cvevent(Deep Learning Specialization, Coursera Oct-2021 Credential ID G8PG2GY6WFS))}}}
   {{{cvevent(Reinforcement Learning Specialization, Coursera Sept-2021
   Credential IDD3LDNU8BRW68)}}}
   {{{cvevent(Introduction to Quantum Computing, Coursera May-2021 Credential ID
   RXQHLEC2WYC8)}}}
#+begin_export latex
\nocite{*}
% \printbibliography[heading=pubtype,title={\printinfo{\faBook}{Books}},type=book]
% \divider
% \printbibliography[heading=pubtype,title={\printinfo{\faFile*[regular]}{Journal Articles}},type=article]
% \divider
\printbibliography[heading=pubtype,title={\printinfo{\faUsers}{Conference Proceedings}},type=inproceedings]
#+end_export

** Preventive Disclosures
   * Gaurav Sood, Ranjith Kumar Gopa, Nandan Kumar Nidhi(May 2024) "Representing
     Tabular Data using Large Lanugage Models"
     https://www.tdcommons.org/dpubs_series/6998/ 
   * Gaurav Sood (Feb 2021) "A Reinforcement Learning Approach to Printer Diagnostics"
     https://www.tdcommons.org/dpubs_series/4244/
   * Gaurav	Sood, Pavleen Kaur Brar, Raghu Anantharangachar (April 2019)
     "Sequence Prediction for Print/Scan Issues using Bayesian Networks"
     https://www.tdcommons.org/dpubs_series/2117/

** Education
{{{cvevent(Msc Research \ Speech Recoginition, Indian Institute of Science Bangalore 2006-2009)}}}
- \faBook Speech Recognition using Support Vector Machines

{{{divider}}}

{{{cvevent(BTech Electronics and Communication Engg, GNE Ludhiana 2001-2005)}}}

\end{paracol}
\end{document}

