* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
  (setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
  (add-to-list 'org-latex-classes
               '("altacv" "\\documentclass[10pt,letter,ragged2e,withhyper]{altacv}
  
  % Change the page layout if you need to
  \\geometry{left=1.25cm,right=1.0cm,top=1.5cm,bottom=1.5cm}
  
  % Use roboto and lato for fonts
  \\renewcommand{\\familydefault}{\\sfdefault}
  
  % Change the colours if you want to
  \\definecolor{SlateGrey}{HTML}{2E2E2E}
  \\definecolor{LightGrey}{HTML}{666666}
  \\definecolor{DarkPastelRed}{HTML}{450808}
  \\definecolor{PastelRed}{HTML}{8F0D0D}
  \\definecolor{GoldenEarth}{HTML}{E7D192}
  \\colorlet{name}{black}
  \\colorlet{tagline}{PastelRed}
  \\colorlet{heading}{DarkPastelRed}
  \\colorlet{headingrule}{GoldenEarth}
  \\colorlet{subheading}{PastelRed}
  \\colorlet{accent}{PastelRed}
  \\colorlet{emphasis}{SlateGrey}
  \\colorlet{body}{LightGrey}
  
  % Change some fonts, if necessary
  \\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
  \\renewcommand{\\personalinfofont}{\\footnotesize}
  \\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
  \\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}
  
  % Change the bullets for itemize and rating marker
  % for \cvskill if you want to
  \\renewcommand{\\itemmarker}{{\\small\\textbullet}}
  \\renewcommand{\\ratingmarker}{\\faCircle}
  "
  
                 ("\\cvsection{%s}" . "\\cvsection*{%s}")
                 ("\\cvevent{%s}" . "\\cvevent*{%s}")))
  (setq org-latex-packages-alist 'nil)
  (setq org-latex-default-packages-alist
        '(("rm" "roboto"  t)
          ("defaultsans" "lato" t)
          ("" "paracol" t)
          ))
#+END_SRC
#+LATEX_CLASS: altacv
#+BEGIN_COMMENT
#+LATEX_HEADER: \columnratio{1.075} % Set the left/right column width ratio to 6:4.
#+END_COMMENT
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
# #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
#+LATEX_HEADER: \addbibresource{aidan.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
#+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings
#+AUTHOR: Gaurav Sood
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Gaurav Sood}
\tagline{Sr. Data Scientist}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  \email{gsood.gaurav@gmail.com}
  \phone{+91 9632714987}
  \location{Bangalore, India}
  \github{github.com/gsood-gaurav}
  \linkedin{linkedin.com/in/gsood-gaurav/}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{1}
#+end_export
** Personal Statement Secondmind :ignore:noexport:
#+begin_export latex
 \begin{quote}
 ``I am an aspiring researcher with interests at the intersection of probabilistic machine learning and control theory. I am particularly interested in uncertainty quantification and as a result, a great deal of my work focuses on Bayesian non-parametric methods, specifically Gaussian processes and variational inference.''
 \end{quote}
#+end_export
** Personal Statement Amazon :ignore:
#+begin_export latex
 \begin{quote}
Data science professional with 8 years of experience in building machine learning models, translating complex data into actionable insights that directly improve operational efficiency. Possessing 14 years of industry experience, I excel at collaborating with cross-functional teams to pinpoint critical business needs and align data science solutions to achieve optimal results.
 \end{quote}
#+end_export
** Skills
{{{cvtag(GenAI)}}}
{{{cvtag(LLMs)}}}
{{{cvtag(NLP)}}}
{{{cvtag(Time Series Forecasting)}}}
{{{cvtag(Reinforcement Learning)}}}
{{{divider}}}

{{{cvtag(Python)}}}
{{{cvtag(PyTorch)}}}
{{{cvtag(TensorFlow/JAX)}}}
{{{cvtag(Julia)}}}
{{{cvtag(Flux/Lux)}}}
{{{cvtag(NumPy)}}}
{{{cvtag(SciPy)}}}
{{{cvtag(Matplotlib)}}}


{{{divider}}}


{{{cvtag(Communication)}}}
{{{cvtag(Leadership Skills)}}}

** Experience
*** Sr Data Scientist                                                :ignore:
{{{cvevent(Sr. Data Scientist, HP Inc. May 2021 -- Ongoing, Bangalore\, India)}}}

- Created Large Language Models(LLMs) Based application for webpage content
  filtering and topic recommendation, adhering to key NFRs which helped in
  acheiving **Net Promoter Score of 65** during beta testing of HP's PrintAI
  program.
- Benchmarked LLM based application's performance on accuracy, cost(token usage)
  and latency, comparing OpenAI, Llama and Mistral, reducing cost by **30%**. 
- Mentored **3** data science interns on automated triaging using Graph Neural
  Networks and LLMs, completed within an expedited time frame of **2 months**.
- Supervised Small Language Models(SLMs, less than **3B** parameters, **4bit**
  quantized) exploration and **instruction finetuning**
  initatives using PEFT acheiving an accuracy of **95%**
- Created Telemetery data analysis pipline processing **0.5** milllion customer
  record using LLM embeddings, BERT, dimensionality reduction(UMAP, Variational
  AutoEncoder) and clustering HDBScan, enhancing operational efficiency by **20%-30%**.
  
{{{cvtag(Prompt Engineering)}}}
{{{cvtag(GPT2)}}}
{{{cvtag(TinyLlama)}}}
{{{Cvtag(FineTuning)}}}
{{{cvtag(Embedding Models)}}}
{{{cvtag(Graph Nerual Networks)}}}

*** Sr. Software Engineer Machine Learning                           :ignore:
{{{par-div}}}
{{{cvevent(Sr. Software Engineer Machine Learning, HP Inc. July 2017 -- May 2021, Bangalore\, India)}}}

- Analyzed the effects of key macro economic indicators on long and short
  term forecasts of product sales data which helped in acheiving on-time
  delivery rate of **90-95%**
- Implemented Hyperparameter Tuning module for Time Series models using Optuna
  reducing the AutoML framework execution time by **20%-25%**
- Worked on HP Personal Systems User Behavior Modelling using Tree Based Models,
  SHAP, UMAP, HDBScan for target marketing campaign.
- Developed simulator environment for online Reinforcement Learning approach to
  automated hardware diagnostics
- Mentored **4** interns on Sequence Tagging Models using BERT, LSTMs,
  Conditional Random Fields for discovering insights in call center records
  which lead to **25%-30%** increase in operational efficency.
- Analyzed **0.1 million** call center record using Bayesian Networks for predictive
  diagnostics as an aid to call center executives and evaluate their decision
  making process

{{{cvtag(Time Series Analysis)}}}
{{{cvtag(Regression)}}}
{{{cvtag(Reinforcement Learning)}}}
{{{cvtag(Probabilistic Graphical Models)}}}
{{{cvtag(Data Annotation)}}}

{{{new-page}}}

** Publications
   * Gaurav Sood, Ranjith Kumar Gopa, Nandan Kumar Nidhi(May 2024) "Representing
     Tabular Data using Large Lanugage Models"
     https://www.tdcommons.org/dpubs_series/6998/ 
   * Gaurav Sood (Feb 2021) "A Reinforcement Learning Approach to Printer Diagnostics"
     https://www.tdcommons.org/dpubs_series/4244/
   * Gaurav	Sood, Pavleen Kaur Brar, Raghu Anantharangachar (April 2019)
     "Sequence Prediction for Print/Scan Issues using Bayesian Networks"
     https://www.tdcommons.org/dpubs_series/2117/

** Education and Certifications
   {{{cvevent(Deep Learning Specialization, DeepLearning.ai Oct-2021)}}}
   {{{cvevent(Reinforcement Learning Specialization, University of Alberta -
   Alberta Machine Intelligence Institute Sept 2021)}}}
   {{{cvevent(MSc Research \ Machine Learning, Indian Institute of Science Bangalore 2006-2009)}}}
- \faBook Speech Recognition using Support Vector Machines

\end{paracol}
\end{document}

